apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userlist
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: userlist
                port:
                  number: 80
