apiVersion: batch/v1
kind: Job
metadata:
  name: userlist-migrate
  labels:
    app: userlist-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: userlist-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: userlist-migrate
          image: jardineiro/otus:hw15
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: userlist-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: APP_EXIT_AFTER_STARTUP
              value: "true"
