apiVersion: v1
kind: Secret
metadata:
  name: billing-db-credentials
  labels:
    app: billing-db
type: Opaque
stringData:
  username: billing
  password: billing-dev-password
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-db-credentials
  labels:
    app: notification-db
type: Opaque
stringData:
  username: notification
  password: notification-dev-password
---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-credentials
  labels:
    app: order-db
type: Opaque
stringData:
  username: order
  password: order-dev-password
