server:
  port: 8080

spring:
  application:
    name: records-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:recordsdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

app:
  user-header: ${USER_HEADER_NAME:X-Username}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
