apiVersion: v1
kind: Secret
metadata:
  name: records-db-credentials
  labels:
    app: records-db
type: Opaque
stringData:
  username: records
  password: records-dev-password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  labels:
    app: keycloak-db
type: Opaque
stringData:
  username: keycloak
  password: keycloak-dev-password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  labels:
    app: keycloak
type: Opaque
stringData:
  username: admin
  password: keycloak-admin-dev-password
