apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hw25

resources:
  - namespace.yaml
  - secrets.yaml
  - billing-db.yaml
  - notification-db.yaml
  - order-db.yaml
  - billing-service.yaml
  - notification-service.yaml
  - order-service.yaml
  - traefik.yaml

configMapGenerator:
  - name: traefik-static-config
    files:
      - traefik-config/traefik.yml
    options:
      labels:
        app: traefik
  - name: traefik-dynamic-config
    files:
      - traefik-config/dynamic.yml
    options:
      labels:
        app: traefik
